### ISSUE TITLE
geist_common still missing after npm install (ts-app)

### ISSUE THREAD

**Issue by sixmoraltales** [faust-computer/example-geist-app#1]
Steps to reproduce:
1. fresh clone of example-geist-app
2. navigate to /ts-app 
3. npm install
4. imports in main.ts will still complain "cannot find module geist_common"

**Comment by Chrismacolor** [comment]
@sixmoraltales Thank you for reporting. We updated the `geist_common` package recently and have not reflected those changes in the example app as yet. I will open a PR to fix this issue.

**Comment by sixmoraltales** [comment]
Awesome, thanks @Chrismacolor!

**Comment by entire** [comment]
@Chrismacolor - i'm on a call with @sixmoraltales - I generated the messages and republished them as v0.1.13 - we are still running into this issue

**Comment by entire** [comment]
@sixmoraltales - should be fixed now with the latest `main`
